### ISSUE TITLE
Pseudo Binary Phase Diagram: Incompatible Dimensions for Cross Product

### ISSUE THREAD

**Issue by mlouis9** [ORNL-CEES/thermochimica#152]
**Describe the bug**
When attempting to compute a pseudo binary phase diagram  for a molten salt system (using the MSTDB-TC 3.0 [here](https://mstdb.ornl.gov/)), the following error is produced when trying to plot the phase diagram:

```Traceback (most recent call last):
  File "/home/mlouis9/thermochimica/python/pseudoBinaryPhaseDiagramGUI.py", line 595, in <module>
    window.read()
  File "/home/mlouis9/thermochimica/python/pseudoBinaryPhaseDiagramGUI.py", line 150, in read
    self.calculation.processPhaseDiagramData()
  File "/home/mlouis9/thermochimica/python/pseudoBinaryPhaseDiagramFunctions.py", line 127, in processPhaseDiagramData
    crossNorms = [np.linalg.norm(np.cross(phaseCompositions[k] - self.plane[0],self.plane[1] - phaseCompositions[k])) for k in range(nPhases)]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mlouis9/thermochimica/python/pseudoBinaryPhaseDiagramFunctions.py", line 127, in <listcomp>
    crossNorms = [np.linalg.norm(np.cross(phaseCompositions[k] - self.plane[0],self.plane[1] - phaseCompositions[k])) for k in range(nPhases)]
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mlouis9/miniconda3/lib/python3.11/site-packages/numpy/core/numeric.py", line 1596, in cross
    raise ValueError(msg)
ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)
```
To calculate the solubility of $\text{PuCl}_3$ in the eutectic salt $\text{LiCl - KCl - PuCl}_3$ ( $0.586(1-x)$ - $0.414(1-x)$ - $x$) where $x$ is the mole fraction of $\text{PuCl}_3$ and the $\text{LiCl-KCl}$ ratio is kept fixed at the (eutectic) ratio $0.586:0.414$ I would like to construct a pseudo binary phase diagram with one endmember as $\text{LiC - KCl}$ ($0.586$ - $0.414$) and the other as $\text{PuCl}_3$. 

**To Reproduce**
Run the script `thermochimica/scripts/pseudoBinaryPhaseDiagramGUI.sh` select the datafile `MSTDB-TC_V3.0_Chlorides_No_Functions_8-2.dat` (available from the MSTDB-TC gitlab [here](https://code.ornl.gov/neams/mstdb). Input the following parameters
- Temperature: 1200
- End Temperature: 500
- \# of steps: 30
- Temperature unit: K
- Pressure: 1
- Pressure unit: atm
- Composition 1:
  - Li: 0.586
  - K: 0.414
  - Cl: 1.0
- Composition 2:
  - Pu: 1.0
  - Cl: 3.0
- \# (composition) steps: 30
- Mass unit: moles
- Use fuzzy stoichiometry: True

**Input**
The desired input should be automatically generated using the GUI

**Expected behavior**
I'd expect a phase diagram plot to appear, which does indeed happen for pseudobinary systems such as $\text{LiCl - KCl}$ and $\text{LiCl - PuCl}_3$, so the issue in this case seems to be having a four dimensional plane (i.e. involving 4 elements rather than 3). I should note that the thermochimica calculation executes correctly, and seems to produce valid output, but it errors when the postprocessing routines are called for creating the plot.

**Screenshots**
The issue is adequately captured in the error message.

**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Compiler: gfortran 11.4.0

**Commit:**
 - Branch: master
 - Commit hash: fc5cdf379c9ad574314ffb63b8237ba392632eb5

**Comment by mlouis9** [comment]
This type of calculation is not currently supported by the Thermochimica pseudoBinaryPhaseDiagramGUI script, but can be executed using standalone calculations. This was resolved by meeting with @markuspiro on Teams.
